# Generated by Django 6.0.7 on 2026-07-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairstyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Hairstyle Categories',
            },
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('travel_fee', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('rating', models.DecimalField(decimal_places=1, default=4.7, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='stylists/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stylists/cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('hairstyle_image', models.ImageField(blank=True, null=True, upload_to='hairstyles')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hairstylecategory')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='booking.stylist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_address', models.TextField()),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairstyle')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.stylist')),
            ],
        ),
    ]
