# Generated by Django 6.0.7 on 2026-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
